[package]
name = "cyth-cgi"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
sqlite = { path = "vendor/sqlite" }
fastcgi = { path = "vendor/fastcgi" }
bcrypt = "0.17.0"
uuid = { version = "1.18.0", features = ["v4"] }
markdown = "1.0.0"
percent-encoding = "2.3.1"
serde_json = "1.0.149"
ureq = "3.3.0"
libc = "0.2.186"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_Networking_WinSock"
]}

[build-dependencies]
cc = "1.2.48"
