name: Build
 
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    concurrency: ci-${{ github.ref }}
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          cargo build --release
          cp target/release/cyth-cgi /home/ubuntu/Desktop/CGI/

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: cyth-cgi
          path: target/release/cyth-cgi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
