name: Build
 
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build
        run: |
          RUSTFLAGS='-C target-feature=+avx2' cargo build --release

      - name: Publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/cyth-cgi
          asset_name: cyth-cgi-linux
          tag: build-${{ github.sha }}
          overwrite: true